const CoreTeamData = [
{
    imgsrc:"/images/core team img/luv.jpg",
    name : "Luv Chadha",
    designation : "President",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"/images/core team img/Aditi.jpg",
    name : "Aditi Aggarwal",
    designation : "Vice President",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"/images/core team img/ayush thakur.jpg",
    name : "Ayush Thakur",
    designation : "Treasurer",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"https://drive.google.com/uc?export=view&id=1m4cVckwcifEN3abc60cRWfCtEnVPnJyS",
    name : "Shreya Khosla",
    designation : "Secratary",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"/images/core team img/srishti ojha.jpg",
    name : "Srishti Ojha",
    designation : "Strategic Chief",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"https://drive.google.com/uc?export=view&id=1w5ARIgxjmUnAHSpaC4FZspUY5v0YSLrj",
    name : "Rohan Chhibber",
    designation : "Strategic Chief",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"https://drive.google.com/uc?export=view&id=1S2CG4GRNqDkBnk1Yfp46k4q3mGGLCo_Q",
    name : "Charvi Gupta",
    designation : "Content Head",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"/images/core team img/naman.jpg",
    name : "Naman Gupta",
    designation : "Technical Head",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"https://drive.google.com/uc?export=view&id=1PfZC5J6NXJbcx9TQ1fC00clBSZE-KgnL",
    name : "Ronit Khatri",
    designation : "Web Master",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"https://drive.google.com/uc?export=view&id=1vkkuAfhutFhGfsgTloJ6swi3yRhTztvO",
    name : "Mehak Mathur",
    designation : "Outreach Head",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"/images/core team img/puru tiwari.jpg",
    name : "Puru Tiwari",
    designation : "Public Relations Head",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"https://drive.google.com/uc?export=view&id=1TPFDrmtdeF5v14-3rwLHxiSshh-2jxEl",
    name : "Nami Jain",
    designation : "Public Relations Head",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"/images/core team img/pallavi.jpg",
    name : "Pallavi Chaudhary",
    designation : "Management Head",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"https://drive.google.com/uc?export=view&id=1zvcmNZ7Jn9WYEEFIL1Ly1R6bp3fDo3Ws",
    name : "Harshul Varshney",
    designation : "Logistics Head",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"https://drive.google.com/uc?export=view&id=1LHLYSQeDryJhLZWJaNNa_hbk90Di6DpV",
    name : "Aarushee Krishna",
    designation : "Digital Head",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"https://drive.google.com/uc?export=view&id=1278PLXkp--lsysheF6l-vW3ER-R_o8OJ",
    name : "Devika Gupta",
    designation : "Digital Head",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"https://drive.google.com/uc?export=view&id=1c95EW8CdxxNfuDTS0lBaeVHozzWiK917",
    name : "Khushi Chauhan",
    designation : "Creative Head",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"https://drive.google.com/uc?export=view&id=1hhnTVpqhRdXIrPdbx1Ty4pMwBF_eoAyo",
    name : "Shreya Arora",
    designation : "Creative Head",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"https://drive.google.com/uc?export=view&id=13rgxfpYclEMht8U7LW4HewGp7Dmq67lw",
    name : "Ishan Verma",
    designation : "Photography Head",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"https://drive.google.com/uc?export=view&id=1wRPSr4MAqI9-ot_GNuOj_PYZI-CEWkso",
    name : "Manas Tripathi",
    designation : "128 Head",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"https://drive.google.com/uc?export=view&id=16mF87M4pRsI27nCjJvvTSO_IwG-XNUEc",
    name : "Pranav Bhargava",
    designation : "128 Management Head",
    instaLink : "/",
    linkedinLink : "/",
},
{
    imgsrc:"/images/core team img/kriti.jpg",
    name : "Kriti Behl",
    designation : "128 Outreach Head",
    instaLink : "/",
    linkedinLink : "/",
}
];

export default CoreTeamData;