const CoreTeamData = [
    {
        imgsrc:"/images/core team img/luv chadha.jpeg",
        name : "Luv Chadha",
        designation : "President",
        instaLink : "https://instagram.com/luvchadha?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/luv-chadha-09443a235",
    },
    {
        imgsrc:"/images/core team img/Aditi.jpeg",
        name : "Aditi Aggarwal",
        designation : "Vice President",
        instaLink : "https://instagram.com/a_diti.1a?igshid=MDM4ZDc5MmU=",
        linkedinLink : "https://www.linkedin.com/in/aditi-aggarwal-50104b1b8",
    },
    {
        imgsrc:"/images/core team img/ayush thakur.jpeg",
        name : "Ayush Thakur",
        designation : "Treasurer",
        instaLink : "https://instagram.com/ayushh17?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/ayush-thakur-b29714216",
    },
    {
        imgsrc:"/images/core team img/shreya.jpeg",
        name : "Shreya Khosla",
        designation : "Secratary",
        instaLink : "https://instagram.com/shreyakhosla11?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/shreya-khosla-9431701b7",
    },
    {
        imgsrc:"/images/core team img/srishti ojha.jpeg",
        name : "Srishti Ojha",
        designation : "Strategic Chief",
        instaLink : "https://instagram.com/srishtiojhaa?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/srishti-ojha-7262b51b3",
    },
    {
        imgsrc:"/images/core team img/rohan chibber.jpeg",
        name : "Rohan Chhibber",
        designation : "Strategic Chief",
        instaLink : "https://instagram.com/chhibbbssss?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/rohan-chhibber-97b7141a1/",
    },
    {
        imgsrc:"/images/core team img/naman.jpeg",
        name : "Naman Gupta",
        designation : "Technical Head",
        instaLink : "https://instagram.com/nemo_.06?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/naman-gupta-nemo",
    },
    {
        imgsrc:"/images/core team img/ronit.jpeg",
        name : "Ronit Khatri",
        designation : "Web Master",
        instaLink : "https://instagram.com/ronitxx9?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/ronit-khatri",
    },
    {
        imgsrc:"/images/core team img/mehak.jpeg",
        name : "Mehak Mathur",
        designation : "Outreach Head",
        instaLink : "https://instagram.com/mmathur112?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/mehak-mathur-842a31219/",
    },
    {
        imgsrc:"/images/core team img/pallavi.jpeg",
        name : "Pallavi Chaudhary",
        designation : "Management Head",
        instaLink : "https://instagram.com/_pallavichaudhary15_?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/pallavi-chaudhary-12a4b020b",
    },
    {
        imgsrc:"/images/core team img/charvi gupta.jpeg",
        name : "Charvi Gupta",
        designation : "Content Head",
        instaLink : "https://instagram.com/charvi.gupta?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/charvi-gupta-898769211",
    },
    {
        imgsrc:"/images/core team img/puru tiwari.jpeg",
        name : "Puru Tiwari",
        designation : "Public Relations Head",
        instaLink : "https://instagram.com/urupp_?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/puru-tiwari-314aab135/",
    },
    {
        imgsrc:"/images/core team img/Nami_Jain.jpeg",
        name : "Nami Jain",
        designation : "Public Relations Head",
        instaLink : "https://instagram.com/nami__jain?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/nami-jain-85b1a21b7/",
    },
    {
        imgsrc:"/images/core team img/harshul.jpeg",
        name : "Harshul Varshney",
        designation : "Logistics Head",
        instaLink : "https://instagram.com/harshul_147?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/harshul-varshney-349a6520b/",
    },
    {
        imgsrc:"/images/core team img/aarushee.jpeg",
        name : "Aarushee Krishna",
        designation : "Digital Head",
        instaLink : "https://instagram.com/aarusheekrishna?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/aarushee-krishna-471667216/",
    },
    {
        imgsrc:"/images/core team img/devika gupta.jpeg",
        name : "Devika Gupta",
        designation : "Digital Head",
        instaLink : "https://instagram.com/devika6001?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/devika-gupta-518643211/",
    },
    {
        imgsrc:"/images/core team img/khushi chauhan.jpeg",
        name : "Khushi Chauhan",
        designation : "Creative Head",
        instaLink : "https://instagram.com/__khushichauhan30?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/khushichauhan23/",
    },
    {
        imgsrc:"/images/core team img/ShreyaArora.jpeg",
        name : "Shreya Arora",
        designation : "Creative Head",
        instaLink : "https://instagram.com/shreya_.arora16?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/shreya-arora-b81064162/",
    },
    {
        imgsrc:"/images/core team img/Ishaan Verma.jpeg",
        name : "Ishaan Verma",
        designation : "Photography Head",
        instaLink : "https://instagram.com/v_ishaan?igshid=ZDdkNTZiNTM=",
        linkedinLink : "https://www.linkedin.com/in/ishaan-verma-8aa2221a4",
    },
    {
        imgsrc:"/images/core team img/Manas_tripathi.jpeg",
        name : "Manas Tripathi",
        designation : "128 Head",
        instaLink : "https://instagram.com/manas_tripathi08?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/tripathimanas25/",
    },
    {
        imgsrc:"/images/core team img/pranav bhargava.jpeg",
        name : "Pranav Bhargava",
        designation : "128 Management Head",
        instaLink : "https://instagram.com/pranavb.01?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/pranav-bhargava-8b03b8203/",
    },
    {
        imgsrc:"/images/core team img/kriti.jpeg",
        name : "Kriti Behl",
        designation : "128 Outreach Head",
        instaLink : "https://instagram.com/kriti_behl?igshid=YmMyMTA2M2Y=",
        linkedinLink : "https://www.linkedin.com/in/kriti-behl/",
    }
    ];
    
    export default CoreTeamData;
