const FoundingMember = [
  {
    imgsrc: "/images/2018-19 alumni/ishan joshi-p.jpeg",
    name: "Ishan Joshi",
    designation: "PRESIDENT",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2018-19 alumni/kuvam uppal-vp.jpeg",
    name: "Kuvam Uppal",
    designation: "Vice President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2018-19 alumni/sanya pandey-treasurer.jpeg",
    name: "Sanya Pandey",
    designation: "Treasurer",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2018-19 alumni/avni handa-secretary.webp",
    name: "Avni Handa",
    designation: "Secretary",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2018-19 alumni/disha jain.jpeg",
    name: "Disha Jain",
    designation: "Member",
    instaLink: "/",
    linkedinLink: "/",
  },
];

const AluminiData2023_24 = [
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324922/2023-24%20alumni/Aman_Tripathi_fyry1a.jpg",
    name: "Aman Tripathi",
    designation: "President",
    instaLink: "https://www.instagram.com/aman_tripathi1609/",
    linkedinLink: "https://www.linkedin.com/in/aman-tripathi-808a4319b/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324923/2023-24%20alumni/Harsh_Sharma_pnej7g.webp",
    name: "Harsh Sharma",
    designation: "Vice President",
    instaLink: "https://www.instagram.com/x_harsh.sharma_x/?hl=en",
    linkedinLink: "https://www.linkedin.com/in/harshsharma20503/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324923/2023-24%20alumni/Mridul_Saraswat_lrjm5r.jpg",
    name: "Mridul Saraswat",
    designation: "Treasurer",
    instaLink: "https://www.instagram.com/saraswat.mridulll/",
    linkedinLink: "https://www.linkedin.com/in/mridul-sarasawat-690853196/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324923/2023-24%20alumni/Anukriti_Mishra_nuzggq.jpg",
    name: "Anukriti Mishra",
    designation: "Secratary",
    instaLink: "https://www.instagram.com/anukriti_mishra._/",
    linkedinLink: "https://www.linkedin.com/in/anukriti-mishra16",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324923/2023-24%20alumni/Aryan_Aggarwal_wvluni.jpg",
    name: "Aryan Agarwal",
    designation: "Strategic Chief",
    instaLink: "https://www.instagram.com/__arynn___/?hl=en",
    linkedinLink: "https://www.linkedin.com/in/aryan-aggarwal-9b8073228/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324921/2023-24%20alumni/Ansh_kilhor_hqf4pa.jpg",
    name: "Ansh kilhor",
    designation: "Strategic Chief",
    instaLink:
      "https://instagram.com/ansh._.05?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D",
    linkedinLink: "https://www.linkedin.com/in/ansh-kilhor-b875b224a",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324923/2023-24%20alumni/KAAVYA_BARANWAL_nqkk2l.jpg",
    name: "Kaavya Baranwal",
    designation: "Technical Head",
    instaLink:
      "https://instagram.com/kaavya.baranwal?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D",
    linkedinLink: "https://www.linkedin.com/in/kaavya-baranwal",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324924/2023-24%20alumni/Nancy_Soni_hojcfu.png",
    name: "Nancy Soni",
    designation: "Outreach Head",
    instaLink:
      "https://instagram.com/nancyysonii?utm_source=qr&igshid=ZDc4ODBmNjlmNQ%3D%3D",
    linkedinLink: "https://www.linkedin.com/in/nancy-soni-3038b31b3",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324928/2023-24%20alumni/sanidhya_agarwal_dhl2lo.jpg",
    name: "Sanidhya Agarwal",
    designation: "Management Head",
    instaLink: "https://www.instagram.com/sanidhya7707/",
    linkedinLink: "https://www.linkedin.com/in/sanidhya-agarwal-887438221/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324926/2023-24%20alumni/Prateeksha_chansoria_sam6el.jpg",
    name: "Prateeksha Chansoria",
    designation: "Management Head",
    instaLink:
      "https://instagram.com/pc_2904?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D",
    linkedinLink: "https://www.linkedin.com/in/prateeksha-chansoria-3a951a23b",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324927/2023-24%20alumni/Rijul_Raj_trlv6o.jpg",
    name: "Rijul Raj",
    designation: "Digital Head",
    instaLink: "https://www.instagram.com/reejool/",
    linkedinLink: "https://www.linkedin.com/in/rijul-raj-660113245/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324922/2023-24%20alumni/Anshul_Chaturvedi_cjizz9.png",
    name: "Anshul Chaturvedi",
    designation: "Digital Head",
    instaLink: "https://www.instagram.com/_anshulchaturvedi_/?hl=en",
    linkedinLink: "https://www.linkedin.com/in/anshul-chaturvedi-50bb54231/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324928/2023-24%20alumni/yashv_creative_vtpcno.jpg",
    name: "Yashvardhan",
    designation: "Creative Head",
    instaLink: "https://instagram.com/yashv_s?igshid=ZDc4ODBmNjlmNQ==",
    linkedinLink: "https://www.linkedin.com/in/yashvardhan-shekhawat-b44b12225",
  },
];

const AluminiData2022_23 = [
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325049/2022-23%20alumni/luv_chadha_guzwkn.jpg",
    name: "Luv Chadha",
    designation: "President",
    instaLink: "https://instagram.com/luvchadha?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/luv-chadha-09443a235",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325044/2022-23%20alumni/Aditi_xq2s2j.jpg",
    name: "Aditi Aggarwal",
    designation: "Vice President",
    instaLink: "https://instagram.com/a_diti.1a?igshid=MDM4ZDc5MmU=",
    linkedinLink: "https://www.linkedin.com/in/aditi-aggarwal-50104b1b8",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325044/2022-23%20alumni/ayush_thakur_ti6xoq.jpg",
    name: "Ayush Thakur",
    designation: "Treasurer",
    instaLink: "https://instagram.com/ayushh17?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/ayush-thakur-b29714216",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325060/2022-23%20alumni/shreya_laeqn5.jpg",
    name: "Shreya Khosla",
    designation: "Secratary",
    instaLink: "https://instagram.com/shreyakhosla11?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/shreya-khosla-9431701b7",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325060/2022-23%20alumni/srishti_ojha_saxiaj.jpg",
    name: "Srishti Ojha",
    designation: "Strategic Chief",
    instaLink: "https://instagram.com/srishtiojhaa?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/srishti-ojha-7262b51b3",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325056/2022-23%20alumni/rohan_chibber_zbhzbe.jpg",
    name: "Rohan Chhibber",
    designation: "Strategic Chief",
    instaLink: "https://instagram.com/chhibbbssss?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/rohan-chhibber-97b7141a1/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325051/2022-23%20alumni/naman_pf55zo.jpg",
    name: "Naman Gupta",
    designation: "Technical Head",
    instaLink: "https://instagram.com/nemo_.06?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/naman-gupta-nemo",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325059/2022-23%20alumni/ronit_fytr3s.jpg",
    name: "Ronit Khatri",
    designation: "Web Master",
    instaLink: "https://instagram.com/ronitxx9?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/ronit-khatri",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325051/2022-23%20alumni/mehak_e1u4ey.jpg",
    name: "Mehak Mathur",
    designation: "Outreach Head",
    instaLink: "https://instagram.com/mmathur112?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/mehak-mathur-842a31219/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325054/2022-23%20alumni/pallavi_pf3qrj.jpg",
    name: "Pallavi Chaudhary",
    designation: "Management Head",
    instaLink: "https://instagram.com/_pallavichaudhary15_?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/pallavi-chaudhary-12a4b020b",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325044/2022-23%20alumni/charvi_gupta_ey8bly.jpg",
    name: "Charvi Gupta",
    designation: "Content Head",
    instaLink: "https://instagram.com/charvi.gupta?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/charvi-gupta-898769211",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325055/2022-23%20alumni/puru_tiwari_bdmvdn.jpg",
    name: "Puru Tiwari",
    designation: "Public Relations Head",
    instaLink: "https://instagram.com/urupp_?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/puru-tiwari-314aab135/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325052/2022-23%20alumni/Nami_Jain_vy4gmx.jpg",
    name: "Nami Jain",
    designation: "Public Relations Head",
    instaLink: "https://instagram.com/nami__jain?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/nami-jain-85b1a21b7/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325045/2022-23%20alumni/harshul_tdtwqq.jpg",
    name: "Harshul Varshney",
    designation: "Logistics Head",
    instaLink: "https://instagram.com/harshul_147?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/harshul-varshney-349a6520b/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325043/2022-23%20alumni/aarushee_jxsig1.jpg",
    name: "Aarushee Krishna",
    designation: "Digital Head",
    instaLink: "https://instagram.com/aarusheekrishna?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/aarushee-krishna-471667216/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325044/2022-23%20alumni/devika_gupta_bzybnh.jpg",
    name: "Devika Gupta",
    designation: "Digital Head",
    instaLink: "https://instagram.com/devika6001?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/devika-gupta-518643211/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325048/2022-23%20alumni/khushi_chauhan_fkpp7f.jpg",
    name: "Khushi Chauhan",
    designation: "Creative Head",
    instaLink: "https://instagram.com/__khushichauhan30?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/khushichauhan23/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325061/2022-23%20alumni/ShreyaArora_egzf0l.jpg",
    name: "Shreya Arora",
    designation: "Creative Head",
    instaLink: "https://instagram.com/shreya_.arora16?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/shreya-arora-b81064162/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325047/2022-23%20alumni/Ishaan_Verma_gnbjpg.jpg",
    name: "Ishaan Verma",
    designation: "Photography Head",
    instaLink: "https://instagram.com/v_ishaan?igshid=ZDdkNTZiNTM=",
    linkedinLink: "https://www.linkedin.com/in/ishaan-verma-8aa2221a4",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325050/2022-23%20alumni/Manas_Tripathi_yp5dyf.jpg",
    name: "Manas Tripathi",
    designation: "128 Head",
    instaLink: "https://instagram.com/manas_tripathi08?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/tripathimanas25/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325055/2022-23%20alumni/pranav_bhargava_mdbbte.jpg",
    name: "Pranav Bhargava",
    designation: "128 Management Head",
    instaLink: "https://instagram.com/pranavb.01?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/pranav-bhargava-8b03b8203/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325048/2022-23%20alumni/kriti_oejeaw.jpg  ",
    name: "Kriti Behl",
    designation: "128 Outreach Head",
    instaLink: "https://instagram.com/kriti_behl?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/kriti-behl/",
  },
];

const AluminiData2021_22 = [
  {
    imgsrc: "/images/2021-22 alumni/ayush singhal.jpeg",
    name: "Ayush Singhal",
    designation: "President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2021-22 alumni/anshika jain.jpeg",
    name: "Anshika Jain",
    designation: "Vice President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2021-22 alumni/Ishan_saxena.jpeg",
    name: "Ishan Saxena",
    designation: "Secretary",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2021-22 alumni/Sparsh_gupta.jpeg",
    name: "Sparsh Gupta",
    designation: "Treasurer",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2021-22 alumni/aayush_mittal.jpeg",
    name: "Aayush Mittal",
    designation: "Strategic Chief",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2021-22 alumni/Tanmay.jpeg",
    name: "Tanmay Rohilla",
    designation: "Strategic Chief",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2021-22 alumni/Roshni.jpeg",
    name: "Roshni Singh",
    designation: "Technical Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2021-22 alumni/Abhishek.jpeg",
    name: "Abhishek Kumar Tamoli",
    designation: "Web Master",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2021-22 alumni/Digvijay.jpeg",
    name: "Digvijay Singh",
    designation: "Outreach Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2021-22 alumni/Harit_mohan.jpeg",
    name: "Harit Mohan",
    designation: "Design Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2021-22 alumni/Somesh.jpeg",
    name: "Somesh Naruka",
    designation: "Digital Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2021-22 alumni/Shweta_duggal.jpeg",
    name: "Shweta Duggal",
    designation: "Operations Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2021-22 alumni/Ritawari_pareek.jpeg",
    name: "Ritawari Pareek",
    designation: "PR Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2021-22 alumni/Ananya.jpeg",
    name: "Ananya Bose",
    designation: "Content & Communications Head",
    instaLink: "/",
    linkedinLink: "/",
  },
];

const AluminiData2020_21 = [
  {
    imgsrc: "/images/2020-21 alumni/divyansh jain.jpeg",
    name: "Divyansh Jain",
    designation: "President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2020-21 alumni/sudip roy.jpeg",
    name: "Sudip Roy",
    designation: "Vice President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2020-21 alumni/divya tyagi.jpeg",
    name: "Divya P Tyagi",
    designation: "Secretary",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2020-21 alumni/hazel.jpeg",
    name: "Hazel Mahajan",
    designation: "Treasurer",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2020-21 alumni/shivam p singh.jpeg",
    name: "Shivam Pratap Singh",
    designation: "Strategic Chief",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2020-21 alumni/chetan gupta.jpeg",
    name: "Chetan Gupta",
    designation: "Technical Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2020-21 alumni/nandini narang.jpeg",
    name: "Nandini Narang",
    designation: "Creative Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2020-21 alumni/anushka aggarwal.jpeg",
    name: "Anushka Agarwal",
    designation: "Outreach Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2020-21 alumni/harshita singh.jpeg",
    name: "Harshita Singh",
    designation: "Digital and Design Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2020-21 alumni/abhishek kamal.jpeg",
    name: "Abhishek Kamal",
    designation: "",
    instaLink: "/",
    linkedinLink: "/",
  },
];

const AluminiData2019_20 = [
  {
    imgsrc: "/images/2019-20 alumni/manan jain.jpeg",
    name: "Manan Jain",
    designation: "President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2019-20 alumni/Akshhat Srivastava.jpeg",
    name: "Akshhat Srivastava",
    designation: "Vice President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2019-20 alumni/Deeksha Varma.jpeg",
    name: "Deeksha Varma",
    designation: "",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2019-20 alumni/Sparsh Goyal.jpeg",
    name: "Sparsh Goyal",
    designation: "Strategic chief",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2019-20 alumni/Khushi Utkarsh.jpeg",
    name: "Khushi Utkarsh",
    designation: "Creative Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "/images/2019-20 alumni/vaibhav.jpeg",
    name: "Vaibhav",
    designation: "Public Relations Head",
    instaLink: "/",
    linkedinLink: "/",
  },
];

export {
  FoundingMember,
  AluminiData2023_24,
  AluminiData2022_23,
  AluminiData2020_21,
  AluminiData2021_22,
  AluminiData2019_20,
};
