const FoundingMember = [
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324792/2018-19%20alumni/ishan_joshi-p_pqpit5.jpg",
    name: "Ishan Joshi",
    designation: "PRESIDENT",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324793/2018-19%20alumni/kuvam_uppal-vp_czaom3.jpg",
    name: "Kuvam Uppal",
    designation: "Vice President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324792/2018-19%20alumni/sanya_pandey-treasurer_ziqh6a.jpg",
    name: "Sanya Pandey",
    designation: "Treasurer",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324352/2018-19%20alumni/avni_handa-secretary_x40rgj.webp",
    name: "Avni Handa",
    designation: "Secretary",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324778/2018-19%20alumni/disha_jain_hz9tz2.jpg",
    name: "Disha Jain",
    designation: "Member",
    instaLink: "/",
    linkedinLink: "/",
  },
];

const AluminiData2024_25=[{
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1738172961/core%20team%20img/Shantanu_rquccf.png",
    name: "Shantanu Pandey",
    designation: "President",
    instaLink:
      "https://www.instagram.com/shantanu_pandey_108?igsh=c3hxZmswODRsaGt6",
    linkedinLink: "https://www.linkedin.com/in/shantanu-pandey-b0609925b",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1738172959/core%20team%20img/Sairaj_e9zkdz.png",
    name: "Sai Raj Singh",
    designation: "Vice President",
    instaLink: "https://www.instagram.com/sairajsingh04?igsh=ZmUwdW40dms1cHk3",
    // linkedinLink: "https://www.linkedin.com/in/sai-raj-singh-67ba28248",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1738172961/core%20team%20img/Tashif_eu7mr1.png",
    name: "Tashif Ahmad Khan",
    designation: "Treasurer",
    instaLink:
      "https://www.instagram.com/khan_tashif?utm_source=qr&igsh=MTVnOThleHFzb3M4aQ==",
    linkedinLink: "https://www.linkedin.com/in/tashif-ahmad-khan-982304244",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1738172962/core%20team%20img/Vaibhav_hsdh2q.jpg",
    name: "Vaibhav Vinayak",
    designation: "Secratary",
    instaLink:
      "https://www.instagram.com/vaibhavvinayak47?igsh=bmY2ZXcxZ2FzdTA0&utm_source=qr",
    linkedinLink: "https://www.linkedin.com/in/vaibhav-vinayak-9690b3172",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1738172960/core%20team%20img/Nandini_jgccau.png",
    name: "Nandini Jindal",
    designation: "Strategic Chief",
    // instaLink: "https://www.instagram.com/",
    linkedinLink: "https://www.linkedin.com/in/nandini-jindal-33a3a7282/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1738172961/core%20team%20img/Sumant_z7k8jb.png",
    name: "Sumant Sharma",
    designation: "Strategic Chief",
    instaLink:
      "https://www.instagram.com/sumant45960?igsh=MXFxN3V3ZHV3dzVxaQ%3D%3D&utm_source=qr",
    linkedinLink: "https://www.linkedin.com/in/sumant-sharma-9ba135244",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1738172960/core%20team%20img/Aryan_ylbro3.png",
    name: "Aryan Goyal",
    designation: "Technical Head",
    instaLink: "https://www.instagram.com/ag_0080/",
    linkedinLink: "https://www.linkedin.com/in/aryangoyal80/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1738172961/core%20team%20img/Rajat_bnwvxt.png",
    name: "Rajat Bhati",
    designation: "Web Master",
    instaLink: "https://www.instagram.com/rajat___.13?igsh=NWVpaWxxMzRpc2ht",
    linkedinLink: "https://www.linkedin.com/in/rajat-bhati-6a2114216",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1738172960/core%20team%20img/Mayer_jvfyv2.jpg",
    name: "Mayer Goyal",
    designation: "Outreach Head",
    instaLink: "https://www.instagram.com/mayer_goyallll/",
    linkedinLink: "https://www.linkedin.com/in/mayer-goyal-07a58527a/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1738172962/core%20team%20img/Yash_z7k74z.png",
    name: "Yash Mittal",
    designation: "Management Head",
    instaLink:
      "https://www.instagram.com/yashmittal_05?igsh=MXI2MGR4YWhwZnQ5Yw==",
    linkedinLink: "https://www.linkedin.com/in/yash-mittal-433307251/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1738172961/core%20team%20img/Navy_xek5gj.png",
    name: "Navy Gautam",
    designation: "Management Head",
    instaLink: "https://www.instagram.com/navy_gautam_/",
    linkedinLink: "https://www.linkedin.com/in/navy-gautam-0247b1249/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1738172959/core%20team%20img/Raunak_exxuvp.jpg",
    name: "Raunak Sharma",
    designation: "Creative Head",
    instaLink:
      "https://www.instagram.com/raunak._.sharma_?igsh=MXFidXd0ZDQxemEwOQ==",
    // linkedinLink: "https://www.linkedin.com/in/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1738172959/core%20team%20img/Adarsh_n7z3eo.jpg",
    name: "Adarsh Sharma",
    designation: "Digital Head",
    instaLink:
      "https://www.instagram.com/adarsh_sharma374?igsh=NW1ldXozcGlkbTAx",
    linkedinLink:
      "https://www.linkedin.com/in/adarsh-sharma-3bb87027b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
  },
];


const AluminiData2023_24 = [
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324922/2023-24%20alumni/Aman_Tripathi_fyry1a.jpg",
    name: "Aman Tripathi",
    designation: "President",
    instaLink: "https://www.instagram.com/aman_tripathi1609/",
    linkedinLink: "https://www.linkedin.com/in/aman-tripathi-808a4319b/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324923/2023-24%20alumni/Harsh_Sharma_pnej7g.webp",
    name: "Harsh Sharma",
    designation: "Vice President",
    instaLink: "https://www.instagram.com/x_harsh.sharma_x/?hl=en",
    linkedinLink: "https://www.linkedin.com/in/harshsharma20503/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324923/2023-24%20alumni/Mridul_Saraswat_lrjm5r.jpg",
    name: "Mridul Saraswat",
    designation: "Treasurer",
    instaLink: "https://www.instagram.com/saraswat.mridulll/",
    linkedinLink: "https://www.linkedin.com/in/mridul-sarasawat-690853196/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324923/2023-24%20alumni/Anukriti_Mishra_nuzggq.jpg",
    name: "Anukriti Mishra",
    designation: "Secratary",
    instaLink: "https://www.instagram.com/anukriti_mishra._/",
    linkedinLink: "https://www.linkedin.com/in/anukriti-mishra16",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324923/2023-24%20alumni/Aryan_Aggarwal_wvluni.jpg",
    name: "Aryan Agarwal",
    designation: "Strategic Chief",
    instaLink: "https://www.instagram.com/__arynn___/?hl=en",
    linkedinLink: "https://www.linkedin.com/in/aryan-aggarwal-9b8073228/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324921/2023-24%20alumni/Ansh_kilhor_hqf4pa.jpg",
    name: "Ansh kilhor",
    designation: "Strategic Chief",
    instaLink:
      "https://instagram.com/ansh._.05?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D",
    linkedinLink: "https://www.linkedin.com/in/ansh-kilhor-b875b224a",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324923/2023-24%20alumni/KAAVYA_BARANWAL_nqkk2l.jpg",
    name: "Kaavya Baranwal",
    designation: "Technical Head",
    instaLink:
      "https://instagram.com/kaavya.baranwal?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D",
    linkedinLink: "https://www.linkedin.com/in/kaavya-baranwal",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324924/2023-24%20alumni/Nancy_Soni_hojcfu.png",
    name: "Nancy Soni",
    designation: "Outreach Head",
    instaLink:
      "https://instagram.com/nancyysonii?utm_source=qr&igshid=ZDc4ODBmNjlmNQ%3D%3D",
    linkedinLink: "https://www.linkedin.com/in/nancy-soni-3038b31b3",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324928/2023-24%20alumni/sanidhya_agarwal_dhl2lo.jpg",
    name: "Sanidhya Agarwal",
    designation: "Management Head",
    instaLink: "https://www.instagram.com/sanidhya7707/",
    linkedinLink: "https://www.linkedin.com/in/sanidhya-agarwal-887438221/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324926/2023-24%20alumni/Prateeksha_chansoria_sam6el.jpg",
    name: "Prateeksha Chansoria",
    designation: "Management Head",
    instaLink:
      "https://instagram.com/pc_2904?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D",
    linkedinLink: "https://www.linkedin.com/in/prateeksha-chansoria-3a951a23b",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324927/2023-24%20alumni/Rijul_Raj_trlv6o.jpg",
    name: "Rijul Raj",
    designation: "Digital Head",
    instaLink: "https://www.instagram.com/reejool/",
    linkedinLink: "https://www.linkedin.com/in/rijul-raj-660113245/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324922/2023-24%20alumni/Anshul_Chaturvedi_cjizz9.png",
    name: "Anshul Chaturvedi",
    designation: "Digital Head",
    instaLink: "https://www.instagram.com/_anshulchaturvedi_/?hl=en",
    linkedinLink: "https://www.linkedin.com/in/anshul-chaturvedi-50bb54231/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324928/2023-24%20alumni/yashv_creative_vtpcno.jpg",
    name: "Yashvardhan",
    designation: "Creative Head",
    instaLink: "https://instagram.com/yashv_s?igshid=ZDc4ODBmNjlmNQ==",
    linkedinLink: "https://www.linkedin.com/in/yashvardhan-shekhawat-b44b12225",
  },
];

const AluminiData2022_23 = [
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325049/2022-23%20alumni/luv_chadha_guzwkn.jpg",
    name: "Luv Chadha",
    designation: "President",
    instaLink: "https://instagram.com/luvchadha?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/luv-chadha-09443a235",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325044/2022-23%20alumni/Aditi_xq2s2j.jpg",
    name: "Aditi Aggarwal",
    designation: "Vice President",
    instaLink: "https://instagram.com/a_diti.1a?igshid=MDM4ZDc5MmU=",
    linkedinLink: "https://www.linkedin.com/in/aditi-aggarwal-50104b1b8",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325044/2022-23%20alumni/ayush_thakur_ti6xoq.jpg",
    name: "Ayush Thakur",
    designation: "Treasurer",
    instaLink: "https://instagram.com/ayushh17?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/ayush-thakur-b29714216",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325060/2022-23%20alumni/shreya_laeqn5.jpg",
    name: "Shreya Khosla",
    designation: "Secratary",
    instaLink: "https://instagram.com/shreyakhosla11?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/shreya-khosla-9431701b7",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325060/2022-23%20alumni/srishti_ojha_saxiaj.jpg",
    name: "Srishti Ojha",
    designation: "Strategic Chief",
    instaLink: "https://instagram.com/srishtiojhaa?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/srishti-ojha-7262b51b3",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325056/2022-23%20alumni/rohan_chibber_zbhzbe.jpg",
    name: "Rohan Chhibber",
    designation: "Strategic Chief",
    instaLink: "https://instagram.com/chhibbbssss?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/rohan-chhibber-97b7141a1/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325051/2022-23%20alumni/naman_pf55zo.jpg",
    name: "Naman Gupta",
    designation: "Technical Head",
    instaLink: "https://instagram.com/nemo_.06?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/naman-gupta-nemo",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325059/2022-23%20alumni/ronit_fytr3s.jpg",
    name: "Ronit Khatri",
    designation: "Web Master",
    instaLink: "https://instagram.com/ronitxx9?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/ronit-khatri",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325051/2022-23%20alumni/mehak_e1u4ey.jpg",
    name: "Mehak Mathur",
    designation: "Outreach Head",
    instaLink: "https://instagram.com/mmathur112?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/mehak-mathur-842a31219/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325054/2022-23%20alumni/pallavi_pf3qrj.jpg",
    name: "Pallavi Chaudhary",
    designation: "Management Head",
    instaLink: "https://instagram.com/_pallavichaudhary15_?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/pallavi-chaudhary-12a4b020b",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325044/2022-23%20alumni/charvi_gupta_ey8bly.jpg",
    name: "Charvi Gupta",
    designation: "Content Head",
    instaLink: "https://instagram.com/charvi.gupta?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/charvi-gupta-898769211",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325055/2022-23%20alumni/puru_tiwari_bdmvdn.jpg",
    name: "Puru Tiwari",
    designation: "Public Relations Head",
    instaLink: "https://instagram.com/urupp_?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/puru-tiwari-314aab135/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325052/2022-23%20alumni/Nami_Jain_vy4gmx.jpg",
    name: "Nami Jain",
    designation: "Public Relations Head",
    instaLink: "https://instagram.com/nami__jain?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/nami-jain-85b1a21b7/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325045/2022-23%20alumni/harshul_tdtwqq.jpg",
    name: "Harshul Varshney",
    designation: "Logistics Head",
    instaLink: "https://instagram.com/harshul_147?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/harshul-varshney-349a6520b/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325043/2022-23%20alumni/aarushee_jxsig1.jpg",
    name: "Aarushee Krishna",
    designation: "Digital Head",
    instaLink: "https://instagram.com/aarusheekrishna?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/aarushee-krishna-471667216/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325044/2022-23%20alumni/devika_gupta_bzybnh.jpg",
    name: "Devika Gupta",
    designation: "Digital Head",
    instaLink: "https://instagram.com/devika6001?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/devika-gupta-518643211/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325048/2022-23%20alumni/khushi_chauhan_fkpp7f.jpg",
    name: "Khushi Chauhan",
    designation: "Creative Head",
    instaLink: "https://instagram.com/__khushichauhan30?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/khushichauhan23/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325061/2022-23%20alumni/ShreyaArora_egzf0l.jpg",
    name: "Shreya Arora",
    designation: "Creative Head",
    instaLink: "https://instagram.com/shreya_.arora16?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/shreya-arora-b81064162/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325047/2022-23%20alumni/Ishaan_Verma_gnbjpg.jpg",
    name: "Ishaan Verma",
    designation: "Photography Head",
    instaLink: "https://instagram.com/v_ishaan?igshid=ZDdkNTZiNTM=",
    linkedinLink: "https://www.linkedin.com/in/ishaan-verma-8aa2221a4",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325050/2022-23%20alumni/Manas_Tripathi_yp5dyf.jpg",
    name: "Manas Tripathi",
    designation: "128 Head",
    instaLink: "https://instagram.com/manas_tripathi08?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/tripathimanas25/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325055/2022-23%20alumni/pranav_bhargava_mdbbte.jpg",
    name: "Pranav Bhargava",
    designation: "128 Management Head",
    instaLink: "https://instagram.com/pranavb.01?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/pranav-bhargava-8b03b8203/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325048/2022-23%20alumni/kriti_oejeaw.jpg  ",
    name: "Kriti Behl",
    designation: "128 Outreach Head",
    instaLink: "https://instagram.com/kriti_behl?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/kriti-behl/",
  },
];

const AluminiData2021_22 = [
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325097/2021-22%20alumni/ayush_singhal_xiztk5.jpg",
    name: "Ayush Singhal",
    designation: "President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325095/2021-22%20alumni/anshika_jain_fi7aam.jpg",
    name: "Anshika Jain",
    designation: "Vice President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325102/2021-22%20alumni/Ishan_saxena_gaztwx.jpg",
    name: "Ishan Saxena",
    designation: "Secretary",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325111/2021-22%20alumni/Sparsh_gupta_iyjdtm.jpg",
    name: "Sparsh Gupta",
    designation: "Treasurer",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325091/2021-22%20alumni/aayush_mittal_hbffmw.jpg",
    name: "Aayush Mittal",
    designation: "Strategic Chief",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325111/2021-22%20alumni/Tanmay_yrsyjc.jpg",
    name: "Tanmay Rohilla",
    designation: "Strategic Chief",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325104/2021-22%20alumni/Roshni_zxfmhs.jpg",
    name: "Roshni Singh",
    designation: "Technical Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325092/2021-22%20alumni/Abhishek_yodhud.jpg",
    name: "Abhishek Kumar Tamoli",
    designation: "Web Master",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325098/2021-22%20alumni/Digvijay_ousaax.jpg",
    name: "Digvijay Singh",
    designation: "Outreach Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325100/2021-22%20alumni/Harit_mohan_unk42g.jpg",
    name: "Harit Mohan",
    designation: "Design Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325108/2021-22%20alumni/Somesh_szfiwv.jpg",
    name: "Somesh Naruka",
    designation: "Digital Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325107/2021-22%20alumni/Shweta_duggal_nq0bwm.jpg",
    name: "Shweta Duggal",
    designation: "Operations Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325103/2021-22%20alumni/Ritawari_pareek_zy2tem.jpg",
    name: "Ritawari Pareek",
    designation: "PR Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325094/2021-22%20alumni/Ananya_wrtupn.jpg",
    name: "Ananya Bose",
    designation: "Content & Communications Head",
    instaLink: "/",
    linkedinLink: "/",
  },
];

const AluminiData2020_21 = [
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325036/2020-21%20alumni/divyansh_jain_kewfx7.jpg",
    name: "Divyansh Jain",
    designation: "President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325043/2020-21%20alumni/sudip_roy_cu5iux.jpg",
    name: "Sudip Roy",
    designation: "Vice President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325035/2020-21%20alumni/divya_tyagi_eer8bd.jpg",
    name: "Divya P Tyagi",
    designation: "Secretary",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325039/2020-21%20alumni/hazel_govknn.jpg",
    name: "Hazel Mahajan",
    designation: "Treasurer",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325042/2020-21%20alumni/shivam_p_singh_e2cvih.jpg",
    name: "Shivam Pratap Singh",
    designation: "Strategic Chief",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325033/2020-21%20alumni/chetan_gupta_x459ts.jpg",
    name: "Chetan Gupta",
    designation: "Technical Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325040/2020-21%20alumni/nandini_narang_m5umyo.jpg",
    name: "Nandini Narang",
    designation: "Creative Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325032/2020-21%20alumni/anushka_aggarwal_y8hnh8.jpg",
    name: "Anushka Agarwal",
    designation: "Outreach Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325037/2020-21%20alumni/harshita_singh_ttpgcr.jpg",
    name: "Harshita Singh",
    designation: "Digital and Design Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325032/2020-21%20alumni/abhishek_kamal_tiijql.jpg",
    name: "Abhishek Kamal",
    designation: "",
    instaLink: "/",
    linkedinLink: "/",
  },
];

const AluminiData2019_20 = [
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324776/2019-20%20alumni/manan_jain_k0iv8y.jpg",
    name: "Manan Jain",
    designation: "President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324744/2019-20%20alumni/Akshhat_Srivastava_txaufb.jpg",
    name: "Akshhat Srivastava",
    designation: "Vice President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324755/2019-20%20alumni/Deeksha_Varma_s1u9wy.jpg",
    name: "Deeksha Varma",
    designation: "",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324790/2019-20%20alumni/Sparsh_Goyal_goo1rk.jpg",
    name: "Sparsh Goyal",
    designation: "Strategic chief",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324765/2019-20%20alumni/Khushi_Utkarsh_n5ma57.jpg",
    name: "Khushi Utkarsh",
    designation: "Creative Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324826/2019-20%20alumni/vaibhav_xmoef0.jpg",
    name: "Vaibhav",
    designation: "Public Relations Head",
    instaLink: "/",
    linkedinLink: "/",
  },
];

export {
  FoundingMember,
  AluminiData2024_25,
  AluminiData2023_24,
  AluminiData2022_23,
  AluminiData2020_21,
  AluminiData2021_22,
  AluminiData2019_20,
};
