const FoundingMember = [
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324792/2018-19%20alumni/ishan_joshi-p_pqpit5.jpg",
    name: "Ishan Joshi",
    designation: "PRESIDENT",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324793/2018-19%20alumni/kuvam_uppal-vp_czaom3.jpg",
    name: "Kuvam Uppal",
    designation: "Vice President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324792/2018-19%20alumni/sanya_pandey-treasurer_ziqh6a.jpg",
    name: "Sanya Pandey",
    designation: "Treasurer",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324352/2018-19%20alumni/avni_handa-secretary_x40rgj.webp",
    name: "Avni Handa",
    designation: "Secretary",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324778/2018-19%20alumni/disha_jain_hz9tz2.jpg",
    name: "Disha Jain",
    designation: "Member",
    instaLink: "/",
    linkedinLink: "/",
  },
];

const AluminiData2023_24 = [
  {
    imgsrc: "/images/2023-2024 alumni/Aman_Tripathi.jpg",
    name: "Aman Tripathi",
    designation: "President",
    instaLink: "https://www.instagram.com/aman_tripathi1609/",
    linkedinLink: "https://www.linkedin.com/in/aman-tripathi-808a4319b/",
  },
  {
    imgsrc: "/images/2023-2024 alumni/Harsh_Sharma.webp",
    name: "Harsh Sharma",
    designation: "Vice President",
    instaLink: "https://www.instagram.com/x_harsh.sharma_x/?hl=en",
    linkedinLink: "https://www.linkedin.com/in/harshsharma20503/",
  },
  {
    imgsrc: "/images/2023-2024 alumni/Mridul_Saraswat.jpg",
    name: "Mridul Saraswat",
    designation: "Treasurer",
    instaLink: "https://www.instagram.com/saraswat.mridulll/",
    linkedinLink: "https://www.linkedin.com/in/mridul-sarasawat-690853196/",
  },
  {
    imgsrc: "/images/2023-2024 alumni/Anukriti_Mishra.jpg",
    name: "Anukriti Mishra",
    designation: "Secratary",
    instaLink: "https://www.instagram.com/anukriti_mishra._/",
    linkedinLink: "https://www.linkedin.com/in/anukriti-mishra16",
  },
  {
    imgsrc: "/images/2023-2024 alumni/Aryan_Aggarwal.jpeg",
    name: "Aryan Agarwal",
    designation: "Strategic Chief",
    instaLink: "https://www.instagram.com/__arynn___/?hl=en",
    linkedinLink: "https://www.linkedin.com/in/aryan-aggarwal-9b8073228/",
  },
  {
    imgsrc: "/images/2023-2024 alumni/Ansh_kilhor.jpg",
    name: "Ansh kilhor",
    designation: "Strategic Chief",
    instaLink:
      "https://instagram.com/ansh._.05?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D",
    linkedinLink: "https://www.linkedin.com/in/ansh-kilhor-b875b224a",
  },
  {
    imgsrc: "/images/2023-2024 alumni/KAAVYA_BARANWAL.jpg",
    name: "Kaavya Baranwal",
    designation: "Technical Head",
    instaLink:
      "https://instagram.com/kaavya.baranwal?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D",
    linkedinLink: "https://www.linkedin.com/in/kaavya-baranwal",
  },
  {
    imgsrc: "/images/2023-2024 alumni/Nancy_Soni.png",
    name: "Nancy Soni",
    designation: "Outreach Head",
    instaLink:
      "https://instagram.com/nancyysonii?utm_source=qr&igshid=ZDc4ODBmNjlmNQ%3D%3D",
    linkedinLink: "https://www.linkedin.com/in/nancy-soni-3038b31b3",
  },
  {
    imgsrc: "/images/2023-2024 alumni/sanidhya_agarwal.jpg",
    name: "Sanidhya Agarwal",
    designation: "Management Head",
    instaLink: "https://www.instagram.com/sanidhya7707/",
    linkedinLink: "https://www.linkedin.com/in/sanidhya-agarwal-887438221/",
  },
  {
    imgsrc: "/images/2023-2024 alumni/Prateeksha_chansoria.jpeg",
    name: "Prateeksha Chansoria",
    designation: "Management Head",
    instaLink:
      "https://instagram.com/pc_2904?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D",
    linkedinLink: "https://www.linkedin.com/in/prateeksha-chansoria-3a951a23b",
  },
  {
    imgsrc: "/images/2023-2024 alumni/Rijul_Raj.jpeg",
    name: "Rijul Raj",
    designation: "Digital Head",
    instaLink: "https://www.instagram.com/reejool/",
    linkedinLink: "https://www.linkedin.com/in/rijul-raj-660113245/",
  },
  {
    imgsrc: "/images/2023-2024 alumni/Anshul_Chaturvedi.png",
    name: "Anshul Chaturvedi",
    designation: "Digital Head",
    instaLink: "https://www.instagram.com/_anshulchaturvedi_/?hl=en",
    linkedinLink: "https://www.linkedin.com/in/anshul-chaturvedi-50bb54231/",
  },
  {
    imgsrc: "/images/2023-2024 alumni/yashv_creative.jpg",
    name: "Yashvardhan",
    designation: "Creative Head",
    instaLink: "https://instagram.com/yashv_s?igshid=ZDc4ODBmNjlmNQ==",
    linkedinLink: "https://www.linkedin.com/in/yashvardhan-shekhawat-b44b12225",
  },
];

const AluminiData2022_23 = [
  {
    imgsrc: "/images/2022-23 alumni/luv chadha.jpeg",
    name: "Luv Chadha",
    designation: "President",
    instaLink: "https://instagram.com/luvchadha?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/luv-chadha-09443a235",
  },
  {
    imgsrc: "/images/2022-23 alumni/Aditi.jpeg",
    name: "Aditi Aggarwal",
    designation: "Vice President",
    instaLink: "https://instagram.com/a_diti.1a?igshid=MDM4ZDc5MmU=",
    linkedinLink: "https://www.linkedin.com/in/aditi-aggarwal-50104b1b8",
  },
  {
    imgsrc: "/images/2022-23 alumni/ayush thakur.jpeg",
    name: "Ayush Thakur",
    designation: "Treasurer",
    instaLink: "https://instagram.com/ayushh17?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/ayush-thakur-b29714216",
  },
  {
    imgsrc: "/images/2022-23 alumni/shreya.jpeg",
    name: "Shreya Khosla",
    designation: "Secratary",
    instaLink: "https://instagram.com/shreyakhosla11?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/shreya-khosla-9431701b7",
  },
  {
    imgsrc: "/images/2022-23 alumni/srishti ojha.jpeg",
    name: "Srishti Ojha",
    designation: "Strategic Chief",
    instaLink: "https://instagram.com/srishtiojhaa?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/srishti-ojha-7262b51b3",
  },
  {
    imgsrc: "/images/2022-23 alumni/rohan chibber.jpeg",
    name: "Rohan Chhibber",
    designation: "Strategic Chief",
    instaLink: "https://instagram.com/chhibbbssss?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/rohan-chhibber-97b7141a1/",
  },
  {
    imgsrc: "/images/2022-23 alumni/naman.jpeg",
    name: "Naman Gupta",
    designation: "Technical Head",
    instaLink: "https://instagram.com/nemo_.06?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/naman-gupta-nemo",
  },
  {
    imgsrc: "/images/2022-23 alumni/ronit.jpeg",
    name: "Ronit Khatri",
    designation: "Web Master",
    instaLink: "https://instagram.com/ronitxx9?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/ronit-khatri",
  },
  {
    imgsrc: "/images/2022-23 alumni/mehak.jpeg",
    name: "Mehak Mathur",
    designation: "Outreach Head",
    instaLink: "https://instagram.com/mmathur112?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/mehak-mathur-842a31219/",
  },
  {
    imgsrc: "/images/2022-23 alumni/pallavi.jpeg",
    name: "Pallavi Chaudhary",
    designation: "Management Head",
    instaLink: "https://instagram.com/_pallavichaudhary15_?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/pallavi-chaudhary-12a4b020b",
  },
  {
    imgsrc: "/images/2022-23 alumni/charvi gupta.jpeg",
    name: "Charvi Gupta",
    designation: "Content Head",
    instaLink: "https://instagram.com/charvi.gupta?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/charvi-gupta-898769211",
  },
  {
    imgsrc: "/images/2022-23 alumni/puru tiwari.jpeg",
    name: "Puru Tiwari",
    designation: "Public Relations Head",
    instaLink: "https://instagram.com/urupp_?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/puru-tiwari-314aab135/",
  },
  {
    imgsrc: "/images/2022-23 alumni/Nami_Jain.jpeg",
    name: "Nami Jain",
    designation: "Public Relations Head",
    instaLink: "https://instagram.com/nami__jain?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/nami-jain-85b1a21b7/",
  },
  {
    imgsrc: "/images/2022-23 alumni/harshul.jpeg",
    name: "Harshul Varshney",
    designation: "Logistics Head",
    instaLink: "https://instagram.com/harshul_147?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/harshul-varshney-349a6520b/",
  },
  {
    imgsrc: "/images/2022-23 alumni/aarushee.jpeg",
    name: "Aarushee Krishna",
    designation: "Digital Head",
    instaLink: "https://instagram.com/aarusheekrishna?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/aarushee-krishna-471667216/",
  },
  {
    imgsrc: "/images/2022-23 alumni/devika gupta.jpeg",
    name: "Devika Gupta",
    designation: "Digital Head",
    instaLink: "https://instagram.com/devika6001?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/devika-gupta-518643211/",
  },
  {
    imgsrc: "/images/2022-23 alumni/khushi chauhan.jpeg",
    name: "Khushi Chauhan",
    designation: "Creative Head",
    instaLink: "https://instagram.com/__khushichauhan30?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/khushichauhan23/",
  },
  {
    imgsrc: "/images/2022-23 alumni/ShreyaArora.jpeg",
    name: "Shreya Arora",
    designation: "Creative Head",
    instaLink: "https://instagram.com/shreya_.arora16?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/shreya-arora-b81064162/",
  },
  {
    imgsrc: "/images/2022-23 alumni/Ishaan Verma.jpeg",
    name: "Ishaan Verma",
    designation: "Photography Head",
    instaLink: "https://instagram.com/v_ishaan?igshid=ZDdkNTZiNTM=",
    linkedinLink: "https://www.linkedin.com/in/ishaan-verma-8aa2221a4",
  },
  {
    imgsrc: "/images/2022-23 alumni/Manas_Tripathi.jpeg",
    name: "Manas Tripathi",
    designation: "128 Head",
    instaLink: "https://instagram.com/manas_tripathi08?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/tripathimanas25/",
  },
  {
    imgsrc: "/images/2022-23 alumni/pranav bhargava.jpeg",
    name: "Pranav Bhargava",
    designation: "128 Management Head",
    instaLink: "https://instagram.com/pranavb.01?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/pranav-bhargava-8b03b8203/",
  },
  {
    imgsrc: "/images/2022-23 alumni/kriti.jpeg",
    name: "Kriti Behl",
    designation: "128 Outreach Head",
    instaLink: "https://instagram.com/kriti_behl?igshid=YmMyMTA2M2Y=",
    linkedinLink: "https://www.linkedin.com/in/kriti-behl/",
  },
];

const AluminiData2021_22 = [
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325097/2021-22%20alumni/ayush_singhal_xiztk5.jpg",
    name: "Ayush Singhal",
    designation: "President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325095/2021-22%20alumni/anshika_jain_fi7aam.jpg",
    name: "Anshika Jain",
    designation: "Vice President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325102/2021-22%20alumni/Ishan_saxena_gaztwx.jpg",
    name: "Ishan Saxena",
    designation: "Secretary",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325111/2021-22%20alumni/Sparsh_gupta_iyjdtm.jpg",
    name: "Sparsh Gupta",
    designation: "Treasurer",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325091/2021-22%20alumni/aayush_mittal_hbffmw.jpg",
    name: "Aayush Mittal",
    designation: "Strategic Chief",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325111/2021-22%20alumni/Tanmay_yrsyjc.jpg",
    name: "Tanmay Rohilla",
    designation: "Strategic Chief",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325104/2021-22%20alumni/Roshni_zxfmhs.jpg",
    name: "Roshni Singh",
    designation: "Technical Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325092/2021-22%20alumni/Abhishek_yodhud.jpg",
    name: "Abhishek Kumar Tamoli",
    designation: "Web Master",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325098/2021-22%20alumni/Digvijay_ousaax.jpg",
    name: "Digvijay Singh",
    designation: "Outreach Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325100/2021-22%20alumni/Harit_mohan_unk42g.jpg",
    name: "Harit Mohan",
    designation: "Design Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325108/2021-22%20alumni/Somesh_szfiwv.jpg",
    name: "Somesh Naruka",
    designation: "Digital Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325107/2021-22%20alumni/Shweta_duggal_nq0bwm.jpg",
    name: "Shweta Duggal",
    designation: "Operations Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325103/2021-22%20alumni/Ritawari_pareek_zy2tem.jpg",
    name: "Ritawari Pareek",
    designation: "PR Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325094/2021-22%20alumni/Ananya_wrtupn.jpg",
    name: "Ananya Bose",
    designation: "Content & Communications Head",
    instaLink: "/",
    linkedinLink: "/",
  },
];

const AluminiData2020_21 = [
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325036/2020-21%20alumni/divyansh_jain_kewfx7.jpg",
    name: "Divyansh Jain",
    designation: "President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325043/2020-21%20alumni/sudip_roy_cu5iux.jpg",
    name: "Sudip Roy",
    designation: "Vice President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325035/2020-21%20alumni/divya_tyagi_eer8bd.jpg",
    name: "Divya P Tyagi",
    designation: "Secretary",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325039/2020-21%20alumni/hazel_govknn.jpg",
    name: "Hazel Mahajan",
    designation: "Treasurer",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325042/2020-21%20alumni/shivam_p_singh_e2cvih.jpg",
    name: "Shivam Pratap Singh",
    designation: "Strategic Chief",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325033/2020-21%20alumni/chetan_gupta_x459ts.jpg",
    name: "Chetan Gupta",
    designation: "Technical Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325040/2020-21%20alumni/nandini_narang_m5umyo.jpg",
    name: "Nandini Narang",
    designation: "Creative Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325032/2020-21%20alumni/anushka_aggarwal_y8hnh8.jpg",
    name: "Anushka Agarwal",
    designation: "Outreach Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325037/2020-21%20alumni/harshita_singh_ttpgcr.jpg",
    name: "Harshita Singh",
    designation: "Digital and Design Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736325032/2020-21%20alumni/abhishek_kamal_tiijql.jpg",
    name: "Abhishek Kamal",
    designation: "",
    instaLink: "/",
    linkedinLink: "/",
  },
];

const AluminiData2019_20 = [
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324776/2019-20%20alumni/manan_jain_k0iv8y.jpg",
    name: "Manan Jain",
    designation: "President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324744/2019-20%20alumni/Akshhat_Srivastava_txaufb.jpg",
    name: "Akshhat Srivastava",
    designation: "Vice President",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324755/2019-20%20alumni/Deeksha_Varma_s1u9wy.jpg",
    name: "Deeksha Varma",
    designation: "",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324790/2019-20%20alumni/Sparsh_Goyal_goo1rk.jpg",
    name: "Sparsh Goyal",
    designation: "Strategic chief",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324765/2019-20%20alumni/Khushi_Utkarsh_n5ma57.jpg",
    name: "Khushi Utkarsh",
    designation: "Creative Head",
    instaLink: "/",
    linkedinLink: "/",
  },
  {
    imgsrc: "https://res.cloudinary.com/dcuc1uetk/image/upload/v1736324826/2019-20%20alumni/vaibhav_xmoef0.jpg",
    name: "Vaibhav",
    designation: "Public Relations Head",
    instaLink: "/",
    linkedinLink: "/",
  },
];

export {
  FoundingMember,
  AluminiData2023_24,
  AluminiData2022_23,
  AluminiData2020_21,
  AluminiData2021_22,
  AluminiData2019_20,
};
